export const GET_SERVICE_REQUESTS = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILURE = 'GET_SERVICE_FAILURE';

export const CREATE_USER = 'CREATE_USER';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
