export const GET_SERVICE_REQUESTS = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILURE = 'GET_SERVICE_FAILURE';
export const LOG_OUT = 'LOG_OUT';
export const LOG_IN = 'LOG_IN';
